# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/refs/heads/main/json-schema/pinact.json
# pinact - https://github.com/suzuki-shunsuke/pinact
version: 3
files:
  - pattern: .github/workflows/*.yml
  - pattern: .github/workflows/*.yaml
  - pattern: .github/actions/*/action.yml
  - pattern: .github/actions/*/action.yaml
  # Ignore everything else, e.g. actions in vendored libs under source

ignore_actions:
  - name: telemetryforge/.*
    ref: main
rules:
  # Skip actions whose ref is a branch name in our own repos.
  - ignore: true
    conditions:
      - expr: |
          ActionRepoOwner == "telemetryforge" && ActionVersion == "22ab1e2f40c0c20b59beb1db70ce804b61b8b719"
