name: Reusable workflow to run container tests
on:
  workflow_call:
    inputs:
      ref:
        description: The commit, SHA or branch to use in this repository.
        required: false
        type: string
        default: main
      image:
        description: The full image name to test.
        required: false
        default: "ghcr.io/fluentdo/agent"
        type: string
      image-tag:
        description: The image tag to test.
        required: true
        type: string
      kind-version:
        description: The version of kind to use for the tests.
        required: true
        type: string
    secrets:
      github-token:
        description: Token to use to pull images from GitHub Container Registry.
        required: true
jobs:
  test-containers:
    name: Test K8S version ${{ inputs.kind-version }} with ${{ inputs.image }}:${{ inputs.image-tag }}
    runs-on: ubuntu-latest
    env:
      FLUENTDO_AGENT_IMAGE: ${{ inputs.image }}
      FLUENTDO_AGENT_TAG: ${{ inputs.image-tag }}
      KIND_VERSION: ${{ inputs.kind-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: FluentDo/agent
          ref: ${{ inputs.ref || github.ref }}
          token: ${{ secrets.github-token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          install_only: true
          # To fix an issue with loading multi-arch images
          # https://github.com/kubernetes-sigs/kind/issues/3795
          version: v0.30.0

      - name: Install BATS
        uses: bats-core/bats-action@3.0.1
        with:
          assert-install: false
          detik-install: false
          file-install: false
          support-install: false

      - name: Install Rush for parallelism
        run: curl -sSfL https://github.com/shenwei356/rush/releases/download/v0.7.0/rush_linux_amd64.tar.gz | sudo tar xzf - -C /usr/local/bin
        shell: bash

      - name: Run integration tests
        run: ./testing/bats/run-k8s-integration-tests.sh
        shell: bash
        env:
          # allow for some parallelity without GNU parallel, since it is not installed by default
          BATS_NO_PARALLELIZE_ACROSS_FILES: 1
          BATS_NUMBER_OF_PARALLEL_JOBS: 4
          BATS_PARALLEL_BINARY_NAME: rush

      # Debugging steps to run if something goes wrong
      - name: Debug - List all pods
        if: always()
        run: kubectl get pods -A
        shell: bash

      - name: Debug - Describe pods
        if: always()
        run: kubectl describe pods -A
        shell: bash
