---
name: Build containers
on:
  workflow_call:
    inputs:
      version:
        description: The version we are building for (as a numeric value 1.2.3).
        required: true
        type: string
      ref:
        description: The commit, SHA or branch to use in this repository.
        required: false
        type: string
        default: main
      dockerhub-username:
        description: The Dockerhub username to use for authenticated pulls.
        required: false
        type: string
        default: "telemetryforge"
      nightly-build-info:
        description: Any special information to add to the nightly build information string.
        required: false
        type: string
        default: ""
      platforms:
        description: JSON array of platforms to build (e.g. '["amd64"]' or '["amd64", "arm64", "s390x"]').
        required: false
        type: string
        default: '["amd64", "arm64", "s390x"]'
    secrets:
      cosign_private_key:
        description: The optional Cosign key to use for signing the images.
        required: false
      cosign_private_key_password:
        description: If the Cosign key requires a password then specify here, otherwise not required.
        required: false
      dockerhub-token:
        description: The Dockerhub token to use for authenticated pulls (not pushes).
        required: true
    outputs:
      version:
        description: The resolved container version tag from docker metadata.
        value: ${{ jobs.build-ubi-container-image-manifest-and-sign.outputs.version }}

env:
  # Set once from repo variable or override here for testing
  STEP_SECURITY_EGRESS_POLICY: ${{ vars.STEP_SECURITY_EGRESS_POLICY || 'audit' }}
  LINUX_AMD_RUNNER: ${{ vars.LINUX_AMD_RUNNER || 'namespace-profile-ubuntu-latest' }}
  LINUX_ARM_RUNNER: ${{ vars.LINUX_ARM_RUNNER || 'namespace-profile-ubuntu-latest-arm' }}
  LINUX_S390X_RUNNER: ${{ vars.LINUX_S390X_RUNNER || 'ubuntu-24.04-s390x' }}
permissions:
  contents: read

jobs:
  # Required as reusable workflow calls cannot reference env variables from the calling workflow but can use outputs from dependent jobs.
  # We use a dedicated job to resolve the image base names so that they can be used in the subsequent jobs and so we have a single source of truth.
  resolve-image-bases:
    name: Resolve image base names
    permissions:
      contents: read
    uses: ./.github/workflows/call-get-image-base-names.yaml

  build-ubi-single-arch-container-images:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
    needs:
      - resolve-image-bases
    uses: ./.github/workflows/call-build-container-single-arch.yaml
    permissions:
      contents: read
      packages: write
    with:
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref }}
      image-base: ${{ needs.resolve-image-bases.outputs.ubi-image-base }}
      definition: Dockerfile.ubi
      dockerhub-username: ${{ inputs.dockerhub-username }}
      platform: ${{ matrix.platform }}
      nightly-build-info: ${{ inputs.nightly-build-info }}
    secrets:
      dockerhub-token: ${{ secrets.dockerhub-token }}

  build-debian-single-arch-container-images:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
    needs:
      - resolve-image-bases
    uses: ./.github/workflows/call-build-container-single-arch.yaml
    permissions:
      contents: read
      packages: write
    with:
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref }}
      image-base: ${{ needs.resolve-image-bases.outputs.debian-image-base }}
      definition: Dockerfile.debian
      dockerhub-username: ${{ inputs.dockerhub-username }}
      platform: ${{ matrix.platform }}
      nightly-build-info: ${{ inputs.nightly-build-info }}
    secrets:
      dockerhub-token: ${{ secrets.dockerhub-token }}

  # Build, publish and sign UBI manifest and expose canonical version output.
  build-ubi-container-image-manifest-and-sign:
    needs:
      - build-ubi-single-arch-container-images
      - resolve-image-bases
    uses: ./.github/workflows/call-build-container-manifest-and-sign.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image-base: ${{ needs.resolve-image-bases.outputs.ubi-image-base }}
    secrets:
      cosign_private_key: ${{ secrets.cosign_private_key }}
      cosign_private_key_password: ${{ secrets.cosign_private_key_password }}

  # Build, publish and sign Debian manifest.
  build-debian-container-image-manifest-and-sign:
    needs:
      - build-debian-single-arch-container-images
      - resolve-image-bases
    uses: ./.github/workflows/call-build-container-manifest-and-sign.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image-base: ${{ needs.resolve-image-bases.outputs.debian-image-base }}
    secrets:
      cosign_private_key: ${{ secrets.cosign_private_key }}
      cosign_private_key_password: ${{ secrets.cosign_private_key_password }}
