name: Lint PRs
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  hadolint-pr:
    runs-on: ubuntu-latest
    name: PR - Hadolint
    steps:
      - uses: actions/checkout@v5
        # Ignores do not work: https://github.com/reviewdog/action-hadolint/issues/35 is resolved
      - uses: reviewdog/action-hadolint@v1

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-shellcheck@v1.32.0
        with:
          reporter: github-pr-review
          fail_level: error
          pattern: |
            *.bash
            *.sh
          exclude: |
            */.git/*
            ./source/*
            ./testing/bats/lib/*

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  prchecker-lint:
    runs-on: ubuntu-latest
    name: PR - Check title format
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
            build
            ci
            docs
            perf
            refactor
            test
            backport
          # Configure which scopes are allowed (newline-delimited).
          # These are regex patterns auto-wrapped in `^ $`.
          # scopes: |
          #   oss
          #   custom
          #   issue-\d+
          # Configure that a scope doe not have to be provided.
          requireScope: false
          # If the PR contains one of these newline-delimited labels, the
          # validation is skipped. If you want to rerun the validation when
          # labels change, you might want to use the `labeled` and `unlabeled`
          # event triggers in your workflow.
          # In this case we want to skip for Dependabot PRs which always have the
          # `dependencies` label: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
          ignoreLabels: |
            dependencies
            ci
            automerge
