name: Lint package change PRs
on:
  pull_request:
    paths:
      - .github/workflows/lint-packages.yaml
      # Run for any CMake or packaging changes
      - 'source/cmake/**'
      - 'source/cpack/**'
      - 'source/init/**'
      - 'source/**/CMakeLists.txt'
      - 'source/packaging/distros/ubuntu/**'
  workflow_dispatch:

jobs:
  build-packages-for-ubuntu:
    name: Building test package for Ubuntu
    uses: ./.github/workflows/call-build-linux-packages.yaml
    with:
      version: '99.9.9'
      ref: ${{ github.ref }}
      target-matrix: '["ubuntu/24.04"]'
      amd-runner-label: ubuntu-latest

  lintian-pr:
    runs-on: ubuntu-latest
    needs:
      - build-packages-for-ubuntu
    name: PR - Lintian (Package changes)
    steps:
      - name: Checkout for config file
        uses: actions/checkout@v5

      - name: Download package
        uses: actions/download-artifact@v6
        with:
          name: package-ubuntu-24.04
          path: downloads/

      - name: Debug
        run: ls -lRh downloads/
        shell: bash

      - name: List contents
        continue-on-error: true
        run: find "downloads/" -name 'fluentdo-agent_*_amd64.deb' -exec dpkg -c {} \;
        shell: bash

      - name: List control files
        continue-on-error: true
        run: |
          find "downloads/" -name 'fluentdo-agent_*_amd64.deb' -exec dpkg -e {} \;
          ls -lRh DEBIAN/
        shell: bash

      - name: Install Lintian
        run: |
          sudo apt-get update
          sudo apt-get install -y lintian
        shell: bash

      - name: Run Lintian
        run: find "downloads/" -name 'fluentdo-agent_*_amd64.deb' -exec lintian --fail-on=error --cfg $PWD/.lintian -c {} \;
        shell: bash
